Added SPM support
RxSwiftCommunity/RxSwiftUtilities pull request #22
Opened 2020-03-27 19:46 UTC by Bernix01

2020-06-26 19:32 UTC, farshadtx commented
Can you please update your PR?

2020-06-27 02:15 UTC, Bernix01 commented
Done @farshadtx

2020-06-27 16:23 UTC, Bernix01 commented
Ready to merge 👍

2020-06-29 17:51 UTC, farshadtx requested changes
Looks good to me, just some extra changes:
- Please add SPM support section to the README file.
- Update podspec to 2.3.0.
- If you don't mind squash all these commits into one.

2020-06-29 17:51 UTC, farshadtx commented on .github/workflows/action.yml
> +    - name: Swift Package manager
I would suggest adding/duplicate another job here. Renaming `tests` to `carthage-tests` and add `spm-tests` to separate the dependency checks and resolve.

2021-12-05 18:45 UTC, merged